# Generated by Django 5.2.5 on 2025-08-22 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_instrument_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='portfolio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trading.portfolio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='portfolio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trading.portfolio'),
            preserve_default=False,
        ),
    ]
