# Generated by Django 5.2.5 on 2025-08-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_alter_holding_portfolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='reset_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
