# Generated by Django 5.2.5 on 2025-08-23 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_portfolio_reset_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.portfolio')),
            ],
        ),
    ]
